name: todo_app
description: A new Flutter project
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  form_field_validator: ^1.0.1
  firebase_core: ^0.4.5
  firebase_auth: ^0.16.0
  google_sign_in: ^4.4.4
  cloud_firestore: ^0.13.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/signin.png
  
  fonts:
      - family: Courgette-Regular
        fonts:
          - asset: assets/fonts/Courgette-Regular.ttf
 



 